services:
 frontend: 
   build: ./project1_FrontEnd
   container_name: frontend_web
   ports: 
   - "5173:5173"
   volumes:
   - ./project1_FrontEnd:/app
   - /app/node_modules
 backend:
    build: ./project1_BackEnd
    container_name: backend_server
    ports:
      - "8000:8000"
    volumes:
      - ./project1_BackEnd:/app
    # mysql:
    #   image: mysql:8.0
    #   container_name: mysql_db
    #   ports:
    #     - "3307:3306"
    #   environment:
    #     MYSQL_DATABASE: luanvan_db
    #     MYSQL_ROOT_PASSWORD: root
    #     MYSQL_USER: laravel
    #     MYSQL_PASSWORD: 
    #   volumes:
    #     - mysql_data:/var/lib/mysql

volumes:
  mysql_data: